# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::931728113463:role/eksctl-cicd-demo-v2-nodegroup-eks-NodeInstanceRole-7D9AFFFFA5VP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
	  - system:masters
      rolearn: arn:aws:iam::931728113463:role/codebuild-cicd-eks-build-service-role
      username: codebuild-cicd-eks-build-service-role  
#    - groups:
#	  - system:masters
#     rolearn: arn:aws:eks:us-east-2:931728113463:cluster/cicd-demo-v2
#     username: cicd-demo-v2   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-02T06:53:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1514"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 80c98ad9-0c93-4ba8-a5f4-61957a83d844
